name: CI

on:
  push:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Ensure module deps
        run: go mod download

      - name: Check go fmt
        shell: bash
        run: |
          set -euo pipefail
          fmtdiff="$(gofmt -l .)"
          if [[ -n "$fmtdiff" ]]; then
            echo "The following files are not 'gofmt'-ed:"
            echo "$fmtdiff"
            exit 1
          fi

      - name: Install staticcheck
        run: go install 'honnef.co/go/tools/cmd/staticcheck@latest'

      - name: Run staticcheck
        run: $(go env GOPATH)/bin/staticcheck ./...

