name: CI

on:
  push:
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'   # or your specific version

      # ✅ Add -cover so coverage prints to the logs
      - name: Run unit tests (with coverage)
        run: go test -cover ./...



