name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run go fmt check
        run: |
          go fmt ./...
          go vet ./...

